module.exports = {
    port: process.env.PORT,
    mongoServerUrl: process.env.MONGOSERVER_URI,
    sessionSecret: process.env.SESSION_SECRET,
    mainGuest: process.env.MAIN_GUEST,
    importantPeople: process.env.IMPORTANT_PEOPLE,
    celebration: process.env.CELEBRATION,
    ticketTemplate: process.env.TICKET_TEMPLATE,
    appQrEndpoint: process.env.APP_ENDPOINT_QR_REDIRECT,
    religiousPlace: process.env.RELIGIOUS_PLACE,
    religiousAddress: process.env.RELIGIOUS_ADDRESS,
    religiousAddressMapsCode: process.env.RELIGIOUS_ADDRESS_MAPSCODE,
    religiousUrl: process.env.RELIGIOUS_URL,
    religiousDateTime: process.env.RELIGIOUS_DATE_TIME,
    // religiousDateTimeObj: new Date(religiousDateTime),
    partyPlace: process.env.PARTY_PLACE,
    partyAddress: process.env.PARTY_ADDRESS,
    partyAddressMapsCode: process.env.PARTY_ADDRESS_MAPSCODE,
    partyUrl: process.env.PARTY_URL,
    partyDateTime: process.env.PARTY_DATE_TIME,
    // partyDateTimeObj: new Date(partyDateTime),
};